#ifndef HANDSOME_CAR_TASK_H
#define HANDSOME_CAR_TASK_H

#ifdef __cplusplus
extern "C" {
#endif

/* These names must exactly match the weak functions generated in freertos.c. */
void InitTaskFunction(void *argument);

/* This name matches the MainTask entry generated by Handsome_Car.ioc. */
void MainTaskFunction(void *argument);

/* This name matches the USBTask entry generated by Handsome_Car.ioc. */
void USBTaskFunction(void *argument);

#ifdef __cplusplus
}
#endif

#endif /* HANDSOME_CAR_TASK_H */
